POST http://localhost:3003/api/blogs
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6Ikp1aG8zIiwiaWQiOiI2NmZhZjI0NTY1YWFmZGE4NWJkZGFhOTIiLCJpYXQiOjE3Mjc3MjIwNzcsImV4cCI6MTcyNzc2MTY3N30.Xs6GVDEtUHTKAihULLvQ5HuPewN1hCQsY3e5IEVcq7c


{
  "title": "REST test4",
  "author": "REST test",
  "url": "www",
  "likes": 0,
  "userId": "66f7d5e06e05da18866fd497"
}